<section id="about">
            <div class="ab-bg-co">
                <h1>About Us</h1>
                <p class="lead2 wid scr-hid">About Us
                Your search for the ideal online stitching service ends right here at Digital Wear. Having provided exceptional ethnic fashion through the digital space to our treasured customers over the years, we have come to understand your fashion needs better. As an extension of our service, we are offering the most skilled, reliable online tailoring service to help you realise your style goals. Our highly professional and, at the same time, customer-centric approach will help you have a pleasant experience in getting customised fashion. Custom stitch -------(write product here)------ in styles and fit that complement you perfectly! When you choose to stitch clothes that suit you, both personality and fit-wise, you end up with the most amazing set of clothes that speak to your style! Our easy-to-understand website and extremely reachable customer care services will guide you step-by-step in fulfilling that dream custom-stitched collection of outfits. With everything that is available online for your convenience, it is only right to offer custom-stitching services for you in the digital world too. No long, tiring and disappointing wait at the tailors shop and struggling to explain to them your style wish; just sit back, let the AC run and browse through ALL imaginable designs right here at one place - at great prices too! Our team of fashion designers will personally design these outfits for you and give the tailor accurate instructions. Yes, you will have your own designer coordinating your style for you!
                You can coordinate your order through call or whatsapp, and share all the necessary details in a way that is comfortable to you. Our pick-up facility will collect the fabric you want stitched; if you need help with selection of fabric - we are here to help you with that too! From buying and selection of fabric of your choice, to picking up add-on style features that will go in the final outfit, we will take care of all the requirements for you. If you want a particular type of embroidery or embellishment on your outfit, our value added services include talented craftspersons that will bring your ideas to life. While you dream of your customised attire, we will work hard to turn it into a gorgeous reality. Customer happiness is our primary goal!
                It will be a sure thrill to see your design sketch transformed into a final outfit when it is delivered to you destination. Our faster stitching and delivery service (currently available only in Himmatnagar) will ensure that your most awaited online order is there for you just when you need it. Go ahead, send us the details of that outfit you’ve been meaning to stitch for so long. You can trust our online stitching site to take your many ideas and transform them into final outfits.
                A stitch in time saves nine, they say, but stitch here at Digital Wear and save more than time - save yourself from ill-fitting clothes and boring fashion!</p>
            </div>
        </section>